VERSION: 2.1
jobs:
  build:
    docker:
      - image: gcc # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run:
         name: Compiling...
         command: gcc -o hello_test main.c
      - run:
         name: Executing...
         command: ./hello_test
  deploy:
    docker:
      - image: nginx
    steps:
      - run:
          name: starting nginx...
          command: rc-service start nginx
