VERSION: 2.1
jobs:
  build:
    docker:
      - image: alpine # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run:
         name: Installing packages
         command: apk add gcc libc-dev
      - run:
         name: Compiling...
         command: gcc -o test main.c
